name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  supervar: DOUGLAS

jobs:
  # Create release branch for the week
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lastname
        run: echo "supervar=Landgraf" >> $GITHUB_ENV

      - name: Read exported variable
        run: |
          echo "$supervar"
          echo "${{ env.supervar }}"
