# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on [push, pull_request]:
workflow_dispatch:
env:
  abbr: DOUGLAS
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Format the date of next Tuesday
        id: tuesday
        run: echo "abbr=$(date '+tuesday%y%m%d')" >> $GITHUB_ENV

      - name: Read exported variable
        run: |
          echo "$abbr"
          echo "${{ env.abbr }}"
